# Use an official Python runtime with Alpine Linux as a base image
FROM python:3.9-alpine

# Set the working directory in the container
WORKDIR /code

# Set the default command
CMD ["python", "solution_test.py"]
